export default function(){
  this.transition(
    this.fromRoute('index'),
    this.toRoute('routines'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.fromRoute('routines'),
    this.toRoute('routines.new'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.fromRoute('routines'),
    this.toRoute('routines.show'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
}
